project_id = "ronxyomoktwjvetuqjee"

[functions.generate-recommendations]
verify_jwt = false

[functions.quality-validation]
verify_jwt = false

[functions.genome-assembly]
verify_jwt = false

[functions.assembly-evaluation]
verify_jwt = false