// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ronxyomoktwjvetuqjee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbnh5b21va3R3anZldHVxamVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzY0MzAsImV4cCI6MjA3MTcxMjQzMH0.3Isr5pZA66JF5hODpu07bfoJtWxxSgLRAC4LkGXcBPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});